# Generated by Django 5.0.7 on 2024-08-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imageLink', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userInformation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userinformation'),
        ),
    ]
