# Generated by Django 5.0.1 on 2024-01-10 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('dateCreate', models.DateTimeField(blank=True, null=True)),
                ('dateClose', models.DateTimeField(blank=True, null=True)),
                ('typeProject', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_node', models.CharField(max_length=150)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('children_folder', models.ManyToManyField(blank=True, related_name='childrenTree', to='repository.childrentree')),
                ('files', models.ManyToManyField(blank=True, to='files.files')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListProjectUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.project')),
            ],
        ),
        migrations.CreateModel(
            name='RootTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameBranch', models.CharField(max_length=150)),
                ('dateCreate', models.DateTimeField(blank=True, null=True)),
                ('childrenFolder', models.ManyToManyField(blank=True, to='repository.childrentree')),
                ('files', models.ManyToManyField(blank=True, to='files.files')),
                ('userCreate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='rootTree',
            field=models.ManyToManyField(blank=True, to='repository.roottree'),
        ),
    ]
