# Generated by Django 5.0.6 on 2024-05-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_project_typelanguage_project_typelicense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typeLicense',
            field=models.CharField(max_length=30),
        ),
    ]
