# Generated by Django 5.0.1 on 2024-01-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=150)),
                ('dateCreate', models.DateTimeField(blank=True, null=True)),
                ('typeComment', models.CharField(default='COMMENT', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('dateCreate', models.DateTimeField(blank=True, null=True)),
                ('labels', models.CharField(max_length=99999, null=True)),
                ('assigned', models.ManyToManyField(blank=True, related_name='assigned', to='users.user')),
            ],
        ),
    ]
