FROM python:3.9


# Instalirajte zavisnosti za Chrome
RUN apt-get update && \
    apt-get install -y wget gnupg2 curl unzip

# Instalirajte Google Chrome
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y google-chrome-stable

# Instalirajte ChromeDriver
RUN wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && \
    mv chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver

# Postavi radni direktorijum
WORKDIR /app

# Kopiraj requirements
COPY requirements.txt .
RUN pip install -r requirements.txt

# Kopiraj ostatak aplikacije
COPY . .

# Instaliraj Selenium i WebDriver Manager za Python
RUN pip install selenium webdriver-manager

# Izloži port na kojem Django aplikacija radi
EXPOSE 8000

# Pokreni Django server
CMD ["python", "manage.py", "test"]
