# Generated by Django 5.0.1 on 2024-01-10 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateCreate', models.DateTimeField(blank=True, null=True)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.project')),
            ],
        ),
    ]
