name: Django CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r myproject/requirements.txt
          pip install selenium chromedriver-autoinstaller

      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get -f install

      - name: Get Chrome Version
        id: get-chrome-version
        run: |
          chrome_version=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          echo "CHROME_VERSION=${chrome_version}" >> $GITHUB_ENV

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          wget "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run migrations
        working-directory: myproject
        run: |
          python manage.py migrate
      
      - name: Start Django server
        working-directory: myproject
        run: |
          python manage.py runserver 0.0.0.0:8000 &
  
      - name: Run tests
        working-directory: myproject
        run: |
          python manage.py test

      - name: Print environment variables
        run: |
          env
  
      - name: List files in the current directory
        run: |
          ls -la

      - name: Check if Django server is up
        run: |
          curl -I http://localhost:8000