name: Django CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r myproject/requirements.txt

      # - name: Install Chrome and ChromeDriver
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y wget
      #     wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb
      #     sudo dpkg -i google-chrome-stable_114.0.5735.90-1_amd64.deb
      #     sudo apt-get -f install
      #     sudo apt-get install -y unzip
      #     wget https://chromedriver.storage.googleapis.com/114.0.5735.16/chromedriver_linux64.zip
      #     unzip chromedriver_linux64.zip
      #     sudo mv chromedriver /usr/local/bin/

      # - name: Run migrations
      #   working-directory: myproject
      #   run: |
      #     python manage.py migrate

      # - name: Run tests
      #   working-directory: myproject
      #   run: |
      #     python manage.py test
