name: Pull Request CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r myproject/requirements.txt
      
      - name: Run tests
        working-directory: myproject
        run: |
          python manage.py test
      
      - name: Upload ChromeDriver log
        uses: actions/upload-artifact@v3
        with:
          name: test-screenshot
          path: screenshot.png
      
      - name: Debug information
        run: |
          echo "Listing directory contents:"
          ls -l
          echo "Current directory:"
          pwd